#!/usr/bin/env python3
"""Convert coffee cup PNG images to RLE-compressed 1BPP C arrays.

Produces include/coffee_cup.h with:
  - COFFEE_MUG[]       (RLE compressed 1BPP)
  - COFFEE_STEAM_0/1/2[] (RLE compressed 1BPP)

RLE format: sequence of (count, byte) pairs.
  - count 1-127: repeat byte that many times
  - count 128+N: copy next N+1 literal bytes (N=0..127)
This handles both solid runs (white areas) and detailed dithered regions.

1BPP: 8 pixels/byte, MSB first. 1=white, 0=black.
Floyd-Steinberg dithered from greyscale source.
"""

from PIL import Image
import os
import sys

SRC_DIR = os.path.dirname(os.path.realpath(__file__))
OUT_FILE = os.path.join(SRC_DIR, "../../include/coffee_cup.h")

def load_and_dither(path, target_w, target_h):
    """Load PNG, resize to fit, Floyd-Steinberg dither to 1-bit."""
    img = Image.open(path).convert("L")
    img.thumbnail((target_w, target_h), Image.LANCZOS)

    canvas = Image.new("L", (target_w, target_h), 255)
    x_off = (target_w - img.width) // 2
    y_off = (target_h - img.height) // 2
    canvas.paste(img, (x_off, y_off))

    bw = canvas.convert("1")
    return bw

def pack_1bpp(img):
    """Pack 1-bit image into bytes, 8 pixels per byte, MSB first."""
    w, h = img.size
    pixels = list(img.getdata())
    packed = []
    row_bytes = (w + 7) // 8

    for y in range(h):
        for bx in range(row_bytes):
            byte = 0
            for bit in range(8):
                px = bx * 8 + bit
                if px < w:
                    idx = y * w + px
                    if pixels[idx]:
                        byte |= (0x80 >> bit)
            packed.append(byte)

    return packed, row_bytes

def rle_compress(data):
    """Simple RLE: run-length for repeating bytes, literal spans for mixed.
    Output format:
      byte 0x00..0x7F (0-127): repeat next byte (count+1) times
      byte 0x80..0xFF (128-255): (byte-128+1) literal bytes follow
    """
    out = []
    i = 0
    n = len(data)

    while i < n:
        # Check for a run of identical bytes
        run_start = i
        while i < n - 1 and data[i] == data[i+1] and (i - run_start) < 127:
            i += 1
        run_len = i - run_start + 1

        if run_len >= 3:
            # Encode as run
            out.append(run_len - 1)  # 0x00..0x7F
            out.append(data[run_start])
            i = run_start + run_len
        else:
            # Collect literals
            lit_start = run_start
            i = run_start
            while i < n:
                # Check if next bytes form a run of 3+
                if i < n - 2 and data[i] == data[i+1] == data[i+2]:
                    break
                i += 1
                if (i - lit_start) >= 128:
                    break

            lit_len = i - lit_start
            if lit_len > 0:
                out.append(0x80 + lit_len - 1)  # 0x80..0xFF
                out.extend(data[lit_start:lit_start + lit_len])

    return out

def to_c_array(name, rle_data, width, height, stride, raw_size):
    """Format as C const array."""
    lines = []
    lines.append(f"#define {name}_W {width}")
    lines.append(f"#define {name}_H {height}")
    lines.append(f"#define {name}_STRIDE {stride}")
    lines.append(f"#define {name}_RAW_SIZE {raw_size}")
    lines.append(f"const uint8_t {name}[] PROGMEM = {{")

    for i in range(0, len(rle_data), 16):
        chunk = rle_data[i:i+16]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {hex_vals},")

    lines.append("};")
    lines.append(f"#define {name}_LEN {len(rle_data)}")
    lines.append("")
    return "\n".join(lines)

def main():
    mug_w, mug_h = 500, 380
    steam_w, steam_h = 400, 450

    files = {
        "COFFEE_MUG": (os.path.join(SRC_DIR, "mug.png"), mug_w, mug_h),
        "COFFEE_STEAM_0": (os.path.join(SRC_DIR, "stage1.png"), steam_w, steam_h),
        "COFFEE_STEAM_1": (os.path.join(SRC_DIR, "stage2.png"), steam_w, steam_h),
        "COFFEE_STEAM_2": (os.path.join(SRC_DIR, "stage3.png"), steam_w, steam_h),
    }

    header = []
    header.append("#pragma once")
    header.append("")
    header.append("#include <pgmspace.h>")
    header.append("#include <stdint.h>")
    header.append("")
    header.append("// Generated by convert_cup.py — do not edit manually")
    header.append("// RLE-compressed 1BPP: 8 pixels/byte, MSB first. 1=white, 0=black.")
    header.append("// RLE: 0x00-0x7F = repeat next byte (N+1) times")
    header.append("//      0x80-0xFF = (N-128+1) literal bytes follow")
    header.append("")

    total_raw = 0
    total_rle = 0

    for name, (path, tw, th) in files.items():
        if not os.path.exists(path):
            print(f"Missing: {path}", file=sys.stderr)
            sys.exit(1)
        bw = load_and_dither(path, tw, th)
        packed, stride = pack_1bpp(bw)
        rle = rle_compress(packed)
        header.append(to_c_array(name, rle, tw, th, stride, len(packed)))

        ratio = len(rle) / len(packed) * 100
        print(f"{name}: {tw}x{th}, raw={len(packed)}, rle={len(rle)} ({ratio:.0f}%)")
        total_raw += len(packed)
        total_rle += len(rle)

        # Save preview
        preview_path = os.path.join(SRC_DIR, f"preview_{name.lower()}.png")
        bw.save(preview_path)

    with open(OUT_FILE, "w") as f:
        f.write("\n".join(header))

    print(f"\nTotal: raw={total_raw//1024}KB, rle={total_rle//1024}KB ({total_rle/total_raw*100:.0f}%)")
    print(f"Wrote {OUT_FILE}")

if __name__ == "__main__":
    main()
