#!/usr/bin/env python3
"""Convert coffee cup PNGs to RLE-compressed 2BPP C arrays.

Produces include/coffee_cup.h with:
  - COFFEE_MUG[]         (RLE compressed 2BPP)
  - COFFEE_STEAM_0/1/2[] (RLE compressed 2BPP)

2BPP: 4 pixels/byte, MSB-first pairs. Values are the panel's ink levels —
0=black, 1=dark gray, 2=light gray, 3=white — matching enum Ink in layout.h.
White (3) is treated as transparent by the blitter, so the cup composites over
whatever is already on screen.

Quantised, NOT dithered. The panel used to be 1bpp, where Floyd-Steinberg was
the only way to suggest a mid-tone; at 2bpp the four levels are real. Dithering
soft gradients like steam into checkerboards is visibly noisy at this size on a
10.3" panel viewed up close, and it compresses far worse — the RLE runs are
destroyed by the alternating pixels.

RLE format (unchanged from the 1bpp version, only the pixel packing differs):
  byte 0x00..0x7F: repeat next byte (count+1) times
  byte 0x80..0xFF: (byte-128+1) literal bytes follow
"""

from PIL import Image
import os
import sys

SRC_DIR = os.path.dirname(os.path.realpath(__file__))
OUT_FILE = os.path.join(SRC_DIR, "../../include/coffee_cup.h")

# Ink levels, and the luminance thresholds that map onto them. The bands are
# deliberately uneven: e-ink greys are not linearly spaced, and the mid-tones
# sit closer to white than a naive 64/128/192 split assumes.
INK_BLACK, INK_DARK, INK_LIGHT, INK_WHITE = 0, 1, 2, 3
THRESHOLDS = [(70, INK_BLACK), (140, INK_DARK), (215, INK_LIGHT)]


def quantise(lum):
    """Map 0-255 luminance to a 2-bit ink level."""
    for limit, ink in THRESHOLDS:
        if lum < limit:
            return ink
    return INK_WHITE


def load_and_quantise(path, target_w, target_h):
    """Load PNG, fit to the target box, quantise to 4 ink levels."""
    img = Image.open(path).convert("L")
    img.thumbnail((target_w, target_h), Image.LANCZOS)

    canvas = Image.new("L", (target_w, target_h), 255)
    canvas.paste(img, ((target_w - img.width) // 2,
                       (target_h - img.height) // 2))
    return [quantise(p) for p in canvas.getdata()]


def pack_2bpp(pixels, w, h):
    """Pack ink levels into bytes, 4 pixels per byte, MSB-first pairs."""
    packed = []
    row_bytes = (w + 3) // 4
    for y in range(h):
        for bx in range(row_bytes):
            byte = 0
            for slot in range(4):
                px = bx * 4 + slot
                ink = pixels[y * w + px] if px < w else INK_WHITE
                byte |= (ink & 0x3) << (6 - slot * 2)
            packed.append(byte)
    return packed, row_bytes


def rle_compress(data):
    out = []
    i = 0
    n = len(data)
    while i < n:
        run_start = i
        while i < n - 1 and data[i] == data[i + 1] and (i - run_start) < 127:
            i += 1
        run_len = i - run_start + 1

        if run_len >= 3:
            out.append(run_len - 1)
            out.append(data[run_start])
            i += 1
        else:
            i = run_start
            lit_start = i
            while i < n and (i - lit_start) < 128:
                if (i < n - 2 and data[i] == data[i + 1] == data[i + 2]):
                    break
                i += 1
            lit_len = i - lit_start
            out.append(128 + lit_len - 1)
            out.extend(data[lit_start:lit_start + lit_len])
    return out


def emit(f, name, rle, w, h, stride, raw_size):
    f.write(f"\n#define {name}_W {w}\n")
    f.write(f"#define {name}_H {h}\n")
    f.write(f"#define {name}_STRIDE {stride}\n")
    f.write(f"#define {name}_RAW_SIZE {raw_size}\n")
    f.write(f"const uint8_t {name}[] PROGMEM = {{\n")
    for i in range(0, len(rle), 16):
        chunk = rle[i:i + 16]
        f.write("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n")
    f.write("};\n")
    f.write(f"#define {name}_LEN {len(rle)}\n")


def convert(f, name, filename, w, h):
    path = os.path.join(SRC_DIR, filename)
    pixels = load_and_quantise(path, w, h)
    packed, stride = pack_2bpp(pixels, w, h)
    rle = rle_compress(packed)
    emit(f, name, rle, w, h, stride, len(packed))
    hist = {lvl: pixels.count(lvl) for lvl in range(4)}
    print(f"  {name:16} {w}x{h} raw {len(packed):6}B rle {len(rle):6}B "
          f"({100*len(rle)//len(packed):3}%)  levels {hist}")
    return len(rle)


def main():
    out_path = os.path.realpath(OUT_FILE)
    print(f"Writing {out_path}")
    total = 0
    with open(out_path, "w") as f:
        f.write("#pragma once\n\n")
        f.write("#include <pgmspace.h>\n#include <stdint.h>\n\n")
        f.write("// Generated by assets/coffee_cup/convert_cup.py — do not edit manually\n")
        f.write("// RLE-compressed 2BPP: 4 pixels/byte, MSB-first pairs.\n")
        f.write("// Ink levels 0=black 1=dark 2=light 3=white; white is transparent.\n")
        f.write("// RLE: 0x00-0x7F = repeat next byte (N+1) times\n")
        f.write("//      0x80-0xFF = (N-128+1) literal bytes follow\n")
        total += convert(f, "COFFEE_MUG", "mug.png", 500, 380)
        for i, src in enumerate(("stage1.png", "stage2.png", "stage3.png")):
            total += convert(f, f"COFFEE_STEAM_{i}", src, 400, 450)
    print(f"total {total} bytes of flash")


if __name__ == "__main__":
    main()
