#include "render.h"
#include <cstdio>
#include <trmnl_log.h>

#ifdef BOARD_TRMNL_X

#include "FastEPD.h"
extern FASTEPD bbep;

// Font headers (Group5 compressed, generated by fontconvert)
#include "fonts/dseg7_clock.h"
#include "fonts/dseg7_data.h"
#include "fonts/dseg7_forecast.h"
#include "fonts/dseg14_text.h"
#include "fonts/ubuntu_labels.h"

// Map FontId enum to font data pointers
static const uint8_t* fontTable[5] = {};

void render_init(void) {
    fontTable[FONT_DSEG7_340]  = dseg7_clock;
    fontTable[FONT_DSEG7_72]   = dseg7_data;
    fontTable[FONT_DSEG7_22]   = dseg7_forecast;
    fontTable[FONT_DSEG14_72]  = dseg14_text;
    fontTable[FONT_UBUNTU_22]  = ubuntu_labels;
    Log_info("Render: fonts loaded (5 faces)");
}

void renderDrawList(const DrawList& dl) {
    Log_info("Render: drawing %d commands", dl.count);

    for (int i = 0; i < dl.count; i++) {
        const DrawCmd& cmd = dl.cmds[i];

        switch (cmd.type) {
        case DRAW_TEXT: {
            const uint8_t* font = fontTable[cmd.text.font];
            if (!font) {
                Log_error("Render: null font for id=%d", cmd.text.font);
                break;
            }
            bbep.setFont(font);
            bbep.setTextColor(BBEP_BLACK, BBEP_WHITE);
            bbep.setCursor(cmd.x, cmd.y);
            bbep.print(cmd.text.text);
            break;
        }
        case DRAW_LINE:
            // drawLine doesn't support thickness directly;
            // draw multiple offset lines for thickness > 1
            for (int t = 0; t < cmd.line.thickness; t++) {
                bool horizontal = (cmd.y == cmd.line.y2);
                int dx = horizontal ? 0 : t;
                int dy = horizontal ? t : 0;
                bbep.drawLine(cmd.x + dx, cmd.y + dy,
                              cmd.line.x2 + dx, cmd.line.y2 + dy,
                              BBEP_BLACK);
            }
            break;

        case DRAW_RECT_FILL:
            bbep.fillRect(cmd.x, cmd.y, cmd.rect.w, cmd.rect.h, BBEP_BLACK);
            break;
        }
    }
}

void renderPartial(const DrawList& dl) {
    bbep.setMode(BB_MODE_1BPP);
    bbep.fillScreen(BBEP_WHITE);
    renderDrawList(dl);
    bbep.partialUpdate(false);
    Log_info("Render: partial refresh done");
}

void renderFull(const DrawList& dl) {
    bbep.setMode(BB_MODE_1BPP);
    bbep.fillScreen(BBEP_WHITE);
    renderDrawList(dl);
    bbep.fullUpdate();
    Log_info("Render: full refresh done");
}

void renderClockPrepare(int prev_hour, int prev_minute) {
    // After deep sleep, pPrevious is lost. Reconstruct it by rendering the
    // previous time into the framebuffer and copying to pPrevious.
    // Everything outside the clock digits is white, so the e-ink won't
    // touch those pixels (no diff = no flash).
    char buf[8];
    bbep.setMode(BB_MODE_1BPP);
    bbep.fillScreen(BBEP_WHITE);
    bbep.setFont(fontTable[FONT_DSEG7_340]);
    bbep.setTextColor(BBEP_BLACK, BBEP_WHITE);
    snprintf(buf, sizeof(buf), "%02d:%02d", prev_hour, prev_minute);
    bbep.setCursor(LAYOUT_CLOCK_X, LAYOUT_CLOCK_Y);
    bbep.print(buf);
    bbep.backupPlane();
    bbep.setPreviousMode(BB_MODE_1BPP);
}

void renderClockUpdate(int hour, int minute) {
    // Render new time into pCurrent and partial-update the clock rows.
    // Assumes pPrevious already reflects what's on screen (either from
    // renderClockPrepare after deep sleep, or from the previous update
    // while awake).
    int y_start = LAYOUT_CLOCK_Y;
    int y_end = LAYOUT_CLOCK_Y + 380;  // 340px font + margin
    char buf[8];

    bbep.fillScreen(BBEP_WHITE);
    bbep.setFont(fontTable[FONT_DSEG7_340]);
    bbep.setTextColor(BBEP_BLACK, BBEP_WHITE);
    snprintf(buf, sizeof(buf), "%02d:%02d", hour, minute);
    bbep.setCursor(LAYOUT_CLOCK_X, LAYOUT_CLOCK_Y);
    bbep.print(buf);

    bbep.partialUpdate(false, y_start, y_end);
    Log_info("Render: clock update %s (rows %d-%d)", buf, y_start, y_end);
}

void renderTimerFrame(const DrawList& dl) {
    bbep.setMode(BB_MODE_1BPP);
    bbep.fillScreen(BBEP_WHITE);
    renderDrawList(dl);
    bbep.partialUpdate(false);
    Log_info("Render: timer frame (%d cmds)", dl.count);
}

#else
// Stub for non-TRMNL_X builds — these functions are never called
void render_init(void) {}
void renderDrawList(const DrawList&) {}
void renderPartial(const DrawList&) {}
void renderFull(const DrawList&) {}
void renderClockPrepare(int, int) {}
void renderClockUpdate(int, int) {}
void renderTimerFrame(const DrawList&) {}
#endif // BOARD_TRMNL_X
